TOP=../..

include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS BELOW HERE

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/db/cavity.db

#----------------------------------------
#  ADD RULES AFTER THIS LINE

include $(TOP)/configure/RULES